### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by tels7ar** [ownaginatious/fbchat-archive-parser#1]
I just tried out fbcap on my messages.htm file.  It begins to process the file, but then it dies as follows:

```
$ fbcap messages.htm
Discovered chat thread with [XXX,YYY,ZZZ]...Traceback (most recent call last):
  File "/usr/local/bin/fbcap", line 9, in <module>
    load_entry_point('fbchat-archive-parser==0.4', 'console_scripts', 'fbcap')()
  File "build/bdist.macosx-10.10-intel/egg/fbchat_archive_parser/main.py", line 66, in main
  File "/Library/Python/2.7/site-packages/clip.py", line 652, in run
    self.invoke(self.parse(tokens))
  File "/Library/Python/2.7/site-packages/clip.py", line 634, in invoke
    self._main.invoke(parsed)
  File "/Library/Python/2.7/site-packages/clip.py", line 519, in invoke
    self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
  File "build/bdist.macosx-10.10-intel/egg/fbchat_archive_parser/main.py", line 27, in fbcap
  File "build/bdist.macosx-10.10-intel/egg/fbchat_archive_parser/parser.py", line 98, in __init__
  File "build/bdist.macosx-10.10-intel/egg/fbchat_archive_parser/parser.py", line 108, in __parse_content
  File "build/bdist.macosx-10.10-intel/egg/fbchat_archive_parser/parser.py", line 174, in __process_element
AttributeError: 'NoneType' object has no attribute 'strip'
```

I tried python 2.7 and 3.5.1 just for fun, same results.

**Comment by ownaginatious** [comment]
Interesting, that would imply that in your `messages.htm` file, you have a thread that lacks information regarding who the participants are. I'm not sure what that means, but seeing as it's rare, I've put in a fix to skip those threads and assume they're corrupted.

I just updated the version of the tool on PyPI (version 0.4.post1). Let me know if that helps!

**Comment by tels7ar** [comment]
That fixed it, thanks.
