### ISSUE TITLE
Issue with CharMap

### ISSUE THREAD

**Issue by LoganWestbury** [ownaginatious/fbchat-archive-parser#10]
Hi again, I am trying to use a different messages.htm file but it is throwing me this error.

```
fbcap ./messages.htm -f stats > stats_div.txt
Discovered chat thread with [*REDACTED*, *REDACTED*l]...
The streaming parser crashed due to malformed XML. Falling back to the less strict/efficient python html.parser. It may
take a while before you see output...
Traceback (most recent call last):
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
76, in fbcap
    fbch = parse_data(parser_call)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
98, in parse_data
    return parser_call()
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\parser.py", lin
e 125, in __init__
    self._parse_content(bs4)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\parser.py", lin
e 146, in _parse_content
    parser=XMLParser(encoding=str('UTF-8'))):
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\xml\etree\ElementTree.py", line 1297, in __next__
    for event in self._parser.read_events():
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\xml\etree\ElementTree.py", line 1279, in read_event
s
    raise event
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\xml\etree\ElementTree.py", line 1237, in feed
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1752, column 1313

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python35-32\Scripts\fbcap-script.py", line 9, in <module>
    load_entry_point('fbchat-archive-parser==0.7.post7', 'console_scripts', 'fbcap')()
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
148, in main
    app.run()
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\clip.py", line 652, in run
    self.invoke(self.parse(tokens))
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\clip.py", line 634, in invoke
    self._main.invoke(parsed)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\clip.py", line 519, in invoke
    self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
93, in fbcap
    raise e
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
82, in fbcap
    fbch = parse_data(partial(parser_call, bs4=True))
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
98, in parse_data
    return parser_call()
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\parser.py", lin
e 125, in __init__
    self._parse_content(bs4)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\parser.py", lin
e 153, in _parse_content
    soup = BeautifulSoup(open(self.stream, 'r').read(), 'html.parser')
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 29414: character maps to <undefined>
```

**Comment by ownaginatious** [comment]
Hey again, thanks for reporting! I believe I have resolved this issue. It looks like your different `messages.htm` file caused a not so common and not-so-well-tested fallback component of the code to fire off. I believe I have fixed it in `0.7.post8`.

Please let me know if that resolves things for you.

And also, just as an aside, the time stamps are now by default in the timezone Facebook reports them in (probably whatever timezone you live in). If you want the UTC behaviour back, please provide the `--utc` command line flag.

**Comment by LoganWestbury** [comment]
Hi there! 

That error seems to have been fixed however it is now throwing this error:

```
 fbcap ./messages_div.htm -f stats > stats_div.txt
Discovered chat thread with  [*REDACTED*, *REDACTED*][39m[39m...
The streaming parser crashed due to malformed XML. Falling back to the less strict/efficient python html.parser. It may
take a while before you see output...
[39m[0mTraceback (most recent call last):
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
89, in fbcap
    fbch = parse_data(parser_call)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
111, in parse_data
    return parser_call()
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\parser.py", lin
e 127, in __init__
    self._parse_content(bs4)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\parser.py", lin
e 148, in _parse_content
    parser=XMLParser(encoding=str('UTF-8'))):
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\xml\etree\ElementTree.py", line 1297, in __next__
    for event in self._parser.read_events():
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\xml\etree\ElementTree.py", line 1279, in read_event
s
    raise event
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\xml\etree\ElementTree.py", line 1237, in feed
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1752, column 1313

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python35-32\Scripts\fbcap-script.py", line 9, in <module>
    load_entry_point('fbchat-archive-parser==0.7.post8', 'console_scripts', 'fbcap')()
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
161, in main
    app.run()
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\clip.py", line 652, in run
    self.invoke(self.parse(tokens))
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\clip.py", line 634, in invoke
    self._main.invoke(parsed)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\clip.py", line 519, in invoke
    self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
106, in fbcap
    raise e
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
95, in fbcap
    fbch = parse_data(partial(parser_call, bs4=True))
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
111, in parse_data
    return parser_call()
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\parser.py", lin
e 127, in __init__
    self._parse_content(bs4)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\parser.py", lin
e 157, in _parse_content
    data = open(self.stream, 'r', encoding='UTF-8').read()
MemoryError
```

**Comment by ownaginatious** [comment]
How large is your `messages.htm` file?

**Comment by LoganWestbury** [comment]
Hi there, the messages.htm is 82,082KB, and the one I used the first time which worked is 61,425KB.

Thanks

**Comment by ownaginatious** [comment]
Hmm yeah, looks like the limit on most modern computers is around 60 MB before it runs out of memory. Coincidentally, someone just posted a similar issue with a 100 MB file. I'm working on a fix now and will let you know!

**Comment by LoganWestbury** [comment]
Thanks for the update!!

**Comment by ownaginatious** [comment]
Hi there, I think I've fixed the issue. Please try version `0.7.post10` and let me know if that fixes it.

**Comment by LoganWestbury** [comment]
Hi there, I have tried that now and the script appears to be doing the same thing except the only error message I get this time is:

`The streaming parser crashed due to malformed XML. Falling back to the less strict/efficient python html.parser. It may
take a while before you see output...`

**Comment by ownaginatious** [comment]
Okay, my hack didn't work as well as I thought it would. I fully implemented illegal XML character scrubbing which *should* prevent it from ever crashing. Sorry for the inconvenience this has caused :/

Try: `0.7.post12`

**Comment by LoganWestbury** [comment]
Hi, it all seems to be working now. Thank you very much for your efforts! :)

**Comment by ownaginatious** [comment]
Glad to hear that fixed it :) :+1:
