### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 5: ordinal not in range(128)

### ISSUE THREAD

**Issue by mmahut** [ownaginatious/fbchat-archive-parser#12]
```
$ fbcap ./messages.htm 
Discovered chat thread with  [,  ]...Traceback (most recent call last):
  File "/usr/bin/fbcap", line 9, in <module>
    load_entry_point('fbchat-archive-parser==0.7.post12', 'console_scripts', 'fbcap')()
  File "/usr/lib/python2.7/site-packages/fbchat_archive_parser/main.py", line 164, in main
    app.run()
  File "/usr/lib/python2.7/site-packages/clip.py", line 652, in run
    self.invoke(self.parse(tokens))
  File "/usr/lib/python2.7/site-packages/clip.py", line 634, in invoke
    self._main.invoke(parsed)
  File "/usr/lib/python2.7/site-packages/clip.py", line 519, in invoke
    self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
  File "/usr/lib/python2.7/site-packages/fbchat_archive_parser/main.py", line 109, in fbcap
    raise e
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 5: ordinal not in range(128)
```

**Comment by ownaginatious** [comment]
Thanks for reporting this! I believe I have fixed the issue. Try version `0.7.post15`.
