### ISSUE TITLE
AttributeError: FacebookChatHistory instance has no attribute 'chat_threads'

### ISSUE THREAD

**Issue by nomeata** [ownaginatious/fbchat-archive-parser#14]
Printing the chat as text works, but running stats fails:
```
Traceback (most recent call last):
  File "/home/jojo/.bin/fbcap", line 11, in <module>
    sys.exit(main())
  File "/home/jojo/.local/lib/python2.7/site-packages/fbchat_archive_parser/main.py", line 154, in main
    app.run()
  File "/home/jojo/.local/lib/python2.7/site-packages/clip.py", line 652, in run
    self.invoke(self.parse(tokens))
  File "/home/jojo/.local/lib/python2.7/site-packages/clip.py", line 634, in invoke
    self._main.invoke(parsed)
  File "/home/jojo/.local/lib/python2.7/site-packages/clip.py", line 519, in invoke
    self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
  File "/home/jojo/.local/lib/python2.7/site-packages/fbchat_archive_parser/main.py", line 96, in fbcap
    generate_stats(fbch, sys.stdout)
  File "/home/jojo/.local/lib/python2.7/site-packages/fbchat_archive_parser/main.py", line 134, in generate_stats
    threads = tuple(fbch.chat_threads[k] for k in fbch.chat_threads.keys())
AttributeError: FacebookChatHistory instance has no attribute 'chat_threads'
```

**Comment by ownaginatious** [comment]
Whoops, consequence of incredibly lacking tests on my part :/ Should be fixed now (`0.7.post16`).
