### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by kevsilberberg** [ownaginatious/fbchat-archive-parser#40]
Hi, when I run the command `fbcap messages.htm` I get the following error and the application halts. I have ensured that the messages.htm is in the correct directory.

```
C:\Python27\Scripts>fbcap messages.htm
Traceback (most recent call last):
  File "C:\Python27\Scripts\fbcap-script.py", line 11, in
    load_entry_point('fbchat-archive-parser==0+unknown', '
ap')()
  File "build\bdist.win-amd64\egg\fbchat_archive_parser\ma
ain
  File "c:\python27\lib\site-packages\clip.py", line 652,
    self.invoke(self.parse(tokens))
  File "c:\python27\lib\site-packages\clip.py", line 634,
    self._main.invoke(parsed)
  File "c:\python27\lib\site-packages\clip.py", line 519,
    self._callback(**{k: v for k, v in iteritems(parsed) i
mmands})
  File "build\bdist.win-amd64\egg\fbchat_archive_parser\ma
bcap
  File "build\bdist.win-amd64\egg\fbchat_archive_parser\pa
 parse
  File "build\bdist.win-amd64\egg\fbchat_archive_parser\pa
 _parse_content
  File "build\bdist.win-amd64\egg\fbchat_archive_parser\pa
 _process_element
  File "build\bdist.win-amd64\egg\fbchat_archive_parser\pa
 _parse_participants
  File "build\bdist.win-amd64\egg\fbchat_archive_parser\na
155, in resolve
  File "build\bdist.win-amd64\egg\fbchat_archive_parser\na
134, in _manual_lookup
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by ownaginatious** [comment]
Whoops, bug from bad manual testing :p Try version `0.9.post12`. That should fix it.
