### ISSUE TITLE
Fail to install fbchat-archive-parser

### ISSUE THREAD

**Issue by weixianggoh** [ownaginatious/fbchat-archive-parser#51]
Hi, newbie here.

I am having a problem in installing this, can anyone feel free to help me and give me some guidance? I really appreciate your time and your help. Thank you

```
bot@bot-Aspire-V5-471PG:~/Desktop/Facebook-Messenger-Bot$ pip install fbchat-archive-parser
Collecting fbchat-archive-parser
Collecting requests==2.13.0 (from fbchat-archive-parser)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting colorama==0.3.7 (from fbchat-archive-parser)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Requirement already satisfied: six==1.10.0 in /usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg (from fbchat-archive-parser)
Collecting beautifulsoup4==4.5.3 (from fbchat-archive-parser)
  Using cached beautifulsoup4-4.5.3-py2-none-any.whl
Collecting pyyaml==3.12 (from fbchat-archive-parser)
Collecting babel==2.4.0 (from fbchat-archive-parser)
  Using cached Babel-2.4.0-py2.py3-none-any.whl
Collecting click==6.7 (from fbchat-archive-parser)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting arrow==0.9.0 (from fbchat-archive-parser)
Collecting python-dateutil==2.6.0 (from fbchat-archive-parser)
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting pytz==2016.7 (from fbchat-archive-parser)
  Using cached pytz-2016.7-py2.py3-none-any.whl
Collecting bs4==0.0.1 (from fbchat-archive-parser)
Installing collected packages: requests, colorama, beautifulsoup4, pyyaml, pytz, babel, click, python-dateutil, arrow, bs4, fbchat-archive-parser
Exception:
Traceback (most recent call last):
  File "/home/bot/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/bot/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/bot/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/bot/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/bot/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/bot/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/bot/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/bot/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/requests'
```

**Comment by weixianggoh** [comment]
```
bot@bot-Aspire-V5-471PG:~/Desktop/Facebook-Messenger-Bot$ sudo pip install fbchat-archive-parser
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==8.1.1', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
