### ISSUE TITLE
Type Error 

### ISSUE THREAD

**Issue by cmanaog** [ownaginatious/fbchat-archive-parser#6]
Hello, I got this error while parsing

Traceback (most recent call last):                                                                                   
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/fbchat_archive_parser/main.py", line 63, in fbcap
    fbch = parse_data(parser_call)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/fbchat_archive_parser/main.py", line 85, in parse_data
    return parser_call()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/fbchat_archive_parser/parser.py", line 124, in __init__
    self._parse_content(bs4)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/fbchat_archive_parser/parser.py", line 145, in _parse_content
    parser=XMLParser(encoding=str('UTF-8'))):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/etree/ElementTree.py", line 1294, in __next__
    for event in self._parser.read_events():
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/etree/ElementTree.py", line 1277, in read_events
    raise event
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/etree/ElementTree.py", line 1235, in feed
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 2151, column 22906

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/fbcap", line 9, in <module>
    load_entry_point('fbchat-archive-parser==0.7', 'console_scripts', 'fbcap')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/fbchat_archive_parser/main.py", line 131, in main
    app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/clip.py", line 652, in run
    self.invoke(self.parse(tokens))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/clip.py", line 634, in invoke
    self._main.invoke(parsed)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/clip.py", line 519, in invoke
    self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/fbchat_archive_parser/main.py", line 80, in fbcap
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/fbchat_archive_parser/main.py", line 68, in fbcap
    fbch = parse_data(parser_call(bs4=True))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/fbchat_archive_parser/main.py", line 85, in parse_data
    return parser_call()
TypeError: 'FacebookChatHistory' object is not callable

**Comment by ownaginatious** [comment]
Hi there! Thanks; stupid syntax error caused that to happen. Should be fixed in version `0.7post1` on PyPI. Please open a new issue if you have any other problems.
