### ISSUE TITLE
Blocking - ValueError: time data does not match format

### ISSUE THREAD

**Issue by HaakonME** [ownaginatious/fbchat-archive-parser#8]
This tool looks really useful, but right now it does not work at all for me - see below. Is this possible to fix? Thank you for your effort!

...Traceback (most recent call last):
  File "/usr/local/bin/fbcap", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/fbchat_archive_parser/main.py", line 137, in main
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/clip.py", line 652, in run
    self.invoke(self.parse(tokens))
  File "/usr/local/lib/python3.5/dist-packages/clip.py", line 634, in invoke
    self._main.invoke(parsed)
  File "/usr/local/lib/python3.5/dist-packages/clip.py", line 519, in invoke
    self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
  File "/usr/local/lib/python3.5/dist-packages/fbchat_archive_parser/main.py", line 87, in fbcap
    raise e
  File "/usr/local/lib/python3.5/dist-packages/fbchat_archive_parser/main.py", line 70, in fbcap
    fbch = parse_data(parser_call)
  File "/usr/local/lib/python3.5/dist-packages/fbchat_archive_parser/main.py", line 92, in parse_data
    return parser_call()
  File "/usr/local/lib/python3.5/dist-packages/fbchat_archive_parser/parser.py", line 124, in __init__
    self._parse_content(bs4)
  File "/usr/local/lib/python3.5/dist-packages/fbchat_archive_parser/parser.py", line 146, in _parse_content
    self._process_element(pos, element)
  File "/usr/local/lib/python3.5/dist-packages/fbchat_archive_parser/parser.py", line 325, in _process_element
    self._parse_time(e)
  File "/usr/local/lib/python3.5/dist-packages/fbchat_archive_parser/parser.py", line 242, in _parse_time
    timestamp = datetime.strptime(timestamp, self._DATE_FORMAT)
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '19. september 2014 kl. 16:00' does not match format '%A, %B %d, %Y at %I:%M%p'

**Comment by ownaginatious** [comment]
Hmm, so it looks like the issue here is that Facebook can apparently give time stamps that are "localized" to the point of being expressed in (probably) the locale/language of the user who dispatched them.

What's stranger here is that `19. september 2014 kl. 16:00` doesn't even appear to include timezone information... so there is no way to easily determine if the time is during daylight savings, without knowing Norway's historical daylight savings schedule, which can lead to issues with message ordering.

Obviously, it's basically impossible for this tool to support every timezone language format (I have no idea why Facebook won't just give UNIX timestamps...). The only easy solution I can think of off the top of my head that is guaranteed to preserve correct message ordering is to change your Facebook language to English (whichever one shouldn't matter) and then initiating a data export.

Sorry for the difficulties :(

**Comment by HaakonME** [comment]
No worries - thanks for the swift reply.
