### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by benbar21** [ownaginatious/fbchat-archive-parser#84]
Hey!

I think I am likely just making a dumb mistake here, but I can't get this to work!

I downloaded the archive, but there is no messages.htm file, but rather a messages.html file. So, I tried with the messages.html file (fbcap messages ./messages.html), but get this error:

```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\python27\scripts\fbcap.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\fbchat_archive_parser\main.py", line 209, in stats
    utc=utc, noprogress=noprogress, resolve=resolve)
  File "c:\python27\lib\site-packages\fbchat_archive_parser\main.py", line 103, in _process_history
    progress_output=not noprogress, use_utc=utc, name_resolver=resolve)
  File "c:\python27\lib\site-packages\fbchat_archive_parser\parser.py", line 532, in parse
    return parser(handle, *args, **kwargs).parse()
  File "c:\python27\lib\site-packages\fbchat_archive_parser\parser.py", line 258, in parse
    self.parse_impl()
  File "c:\python27\lib\site-packages\fbchat_archive_parser\parser.py", line 490, in parse_impl
    self.user, thread_references = self._get_manifest_data()
  File "c:\python27\lib\site-packages\fbchat_archive_parser\parser.py", line 441, in _get_manifest_data
    user = element.text.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

I'd appreciate any help!

Ben

**Comment by ownaginatious** [comment]
Looks like Facebook changed the format again and finally made a proper interface for this, probably to comply with the new GDPR laws by the European Union.

In light of that, I'm going to deprecate this project as Facebook has finally solved the problem on their end as far as I'm concerned.

If you would like your conversation data in text format, it's fairly trivial to convert from the JSON formatted messages, which they're now offering.

**Comment by benbar21** [comment]
At least I'm not crazy!

I was actually more hoping to get some stats - I, along with others I'm sure, would be very happy if you changed this project into something which generates states from the jsons.

Ben

**Comment by ownaginatious** [comment]
Something like that would be nice, but I feel like it's a significant enough change that it might as well be a new project entirely. I'm kind of burned out on this one, to be honest, due to all the weird irregularities of the old formats that constantly needed to be tweaked (timestamps in localized date formats, out-of-order messages, duplicate messages, illegal HTML characters. etc).

I'll let someone else pickup the torch :p

**Comment by benbar21** [comment]
That's fair! I might try to play around with it a bit, but hopefully someone else who knows more than me'll make something good!
