### ISSUE TITLE
Issue with ValueError time data does not match format

### ISSUE THREAD

**Issue by LoganWestbury** [ownaginatious/fbchat-archive-parser#9]
```
``C:\Users\*REDACTED*\Documents\Powershell\messages\all>fbcap ./messages.htm
Discovered chat thread with [*REDACTED*, *REDACTED*]...Traceback (most recent call last):
  File "C:\Users\*REDACTED*\AppData\Local\Programs\Python\Python35-32\Scripts\fbcap-script.py", line 9, in <module>
    load_entry_point('fbchat-archive-parser==0.7.post2', 'console_scripts', 'fbcap')()
  File "c:\users\*REDACTED*\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line 137, in main
    app.run()
  File "c:\users\*REDACTED*\appdata\local\programs\python\python35-32\lib\site-packages\clip.py", line 652, in run
    self.invoke(self.parse(tokens))
  File "c:\users\*REDACTED*\appdata\local\programs\python\python35-32\lib\site-packages\clip.py", line 634, in invoke
    self._main.invoke(parsed)
  File "c:\users\*REDACTED*\appdata\local\programs\python\python35-32\lib\site-packages\clip.py", line 519, in invoke
    self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
  File "c:\users\*REDACTED*\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line 87, in fbcap
    raise e
  File "c:\users\*REDACTED*\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line 70, in fbcap
    fbch = parse_data(parser_call)
  File "c:\users\*REDACTED*\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line 92, in parse_data
    return parser_call()
  File "c:\users\*REDACTED*\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\parser.py", line 124, in __init__
    self._parse_content(bs4)
  File "c:\users\*REDACTED*\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\parser.py", line 146, in _parse_content
    self._process_element(pos, element)
  File "c:\users\*REDACTED*\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\parser.py", line 325, in _process_element
    self._parse_time(e)
  File "c:\users\*REDACTED*\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\parser.py", line 242, in _parse_time
    timestamp = datetime.strptime(timestamp, self._DATE_FORMAT)
  File "c:\users\*REDACTED*\appdata\local\programs\python\python35-32\lib\_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "c:\users\*REDACTED*\appdata\local\programs\python\python35-32\lib\_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data 'Saturday, 9 July 2016 at 21:50' does not match format '%A, %B %d, %Y at %I:%M%p'
```

**Comment by CrinklyMilk** [comment]
Error when trying to use "fbcap ./messages.htm" 

Windows 10 64Bit, Python35-32

**Comment by ownaginatious** [comment]
Hi there, thanks for reporting this issue!

I believe the issue was caused by the fact that I only expected 12-hour formatted time stamps. I modified it to also support 24-hour time stamps, like in your example.

Please try the new version `0.7.post5` and respond to this ticket if you're still having issues.

**Comment by LoganWestbury** [comment]
Hi there. That seems to have worked fine. However when the script comes across an emoji like this:


It is throwing this error.

`[2016-06-19 07:32Z] Logan Westbury: Traceback (most recent call last):
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python35-32\Scripts\fbcap-script.py", line 9, in <module>
    load_entry_point('fbchat-archive-parser==0.7.post5', 'console_scripts', 'fbcap')()
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
142, in main
    app.run()
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\clip.py", line 652, in run
    self.invoke(self.parse(tokens))
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\clip.py", line 634, in invoke
    self._main.invoke(parsed)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\clip.py", line 519, in invoke
    self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
87, in fbcap
    raise e
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\main.py", line
80, in fbcap
    write(format, fbch)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\writers\__init_
_.py", line 18, in write
    item().write(data)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\writers\writer.
py", line 14, in write
    return self.write_history(data)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\writers\text.py
", line 30, in write_history
    self.write_thread(history.chat_threads[k], stream)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\writers\text.py
", line 40, in write_thread
    self.write_message(message, stream)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\fbchat_archive_parser\writers\text.py
", line 51, in write_message
    stream.write('%s\n' % lines[0])
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 40, in
 write
    self.__convertor.write(text)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 141, i
n write
    self.write_and_convert(text)
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 169, i
n write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 174, i
n write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\logan\appdata\local\programs\python\python35-32\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 16-17: character maps to <undefined>`

Attached is a screenshot from Facebook of the message right after the last one displayed. Also attached is a screenshot of the console.

<img width="71" alt="firefox_2016-09-21_17-36-49" src="https://cloud.githubusercontent.com/assets/2437782/18720075/175f8e20-8022-11e6-818c-eefd9229aaf8.png">

<img width="1434" alt="powershell_2016-09-21_17-38-00" src="https://cloud.githubusercontent.com/assets/2437782/18720166/7ae03404-8022-11e6-9c0c-a0bd96ba88fa.png">

**Comment by ownaginatious** [comment]
Hey there. Weird... that isn't supposed to be an issue under Python 3, which I see you're using. Could be a Windows-specific issue. I've added a patch that should correct the behaviour (`0.7post6`).

Please let me know if that helps.

**Comment by LoganWestbury** [comment]
That is working perfectly. Thank you very much!
